export const INVENTORIES_READ_START = "INVENTORIES_READ_START";
export const INVENTORIES_READ_OK = "INVENTORIES_READ_OK";
export const INVENTORIES_READ_ERROR = "INVENTORIES_READ_ERROR";

export const INVENTORIES_SELL_START = "INVENTORIES_SELL_START";
export const INVENTORIES_SELL_OK = "INVENTORIES_SELL_OK";
export const INVENTORIES_SELL_ERROR = "INVENTORIES_SELL_ERROR";
