export const VENDORS_READ_START = "VENDORS_READ_START";
export const VENDORS_READ_OK = "VENDORS_READ_OK";
export const VENDORS_READ_ERROR = "VENDORS_READ_ERROR";

export const VENDORS_CREATE = "VENDORS_CREATE";
export const VENDORS_EDIT = "VENDORS_EDIT";
export const VENDORS_DELETE = "VENDORS_DELETE";
