export const PRODUCTS_READ_START = "PRODUCTS_READ_START";
export const PRODUCTS_READ_OK = "PRODUCTS_READ_OK";
export const PRODUCTS_READ_ERROR = "PRODUCTS_READ_ERROR";

export const PRODUCTS_CREATE = "PRODUCTS_CREATE";
export const PRODUCTS_EDIT = "PRODUCTS_EDIT";
export const PRODUCTS_DELETE = "PRODUCTS_DELETE";
